# Generated by Django 2.1.5 on 2019-09-07 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_card', models.TextField()),
                ('back_card', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='cards',
            new_name='Card_Set',
        ),
        migrations.AddField(
            model_name='card',
            name='parent_card_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.Card_Set'),
        ),
    ]
