# Generated by Django 2.1.5 on 2019-09-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_auto_20190907_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='parent_card_set',
        ),
        migrations.RenameField(
            model_name='card_set',
            old_name='definition',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='card_set',
            old_name='word',
            new_name='topic',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
