# Generated by Django 2.1.5 on 2019-09-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_auto_20190908_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('definition', models.TextField()),
                ('parent_card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.Card_Set')),
            ],
        ),
    ]
