# Generated by Django 2.1.5 on 2019-09-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Write_Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='word',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='card_set',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
