# Generated by Django 2.1.5 on 2019-09-28 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_auto_20190928_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='write_sentence',
            name='post',
        ),
        migrations.AddField(
            model_name='write_sentence',
            name='parent_card',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='flashcards.Card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='write_sentence',
            name='sentence',
            field=models.TextField(blank=True, default='Sentence', max_length=500, null=True),
        ),
    ]
