# Generated by Django 2.1.5 on 2019-09-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_auto_20190928_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='write_sentence',
            name='parent_card',
        ),
        migrations.AddField(
            model_name='card',
            name='sentence',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Write_Sentence',
        ),
    ]
