# Generated by Django 2.1.5 on 2019-09-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0011_auto_20190928_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='sentence',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
