# Generated by Django 2.1.5 on 2019-09-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_auto_20190928_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='sentence',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
