# Generated by Django 2.1.5 on 2019-09-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0013_auto_20190928_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='sentence',
        ),
        migrations.AddField(
            model_name='card',
            name='sentences',
            field=models.TextField(blank=True),
        ),
    ]
