# Generated by Django 2.1.5 on 2019-11-23 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0014_auto_20190928_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
