# Generated by Django 2.1.5 on 2019-12-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0015_delete_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='sentences',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
